#configuration database
spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/backendservice
    username: dicka
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
server:
  port: 8888
#config file upload
---
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
#folder location save file
file:
  upload-dir: /home/dicka/Documents/project-java/spring-reactjs/uploads
jwt:
  expired:
    inms: 3600000
    key: so6DwmPfSBbDargyQvOGw6RW8vSDz5+LpkCaVwxcbAORYVi9r2YuOYAL2tocMG9JGqAfUzDqBRhqo/hKJZVd2g==